[package]
name = "hayom"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = [
  "crates/*",
]

[workspace.dependencies]
jiff = "0.2.15"
lunar = { path = "./crates/lunar" }
solar = { path = "./crates/solar" }
thiserror = "2.0.17"
